### PR TITLE
Updated Makefile for linking -lcrypt fix

### PR DESCRIPTION
**Pull request by gpiedimonte**
I don't know why but -lcrypt must placed at the end of line, not at the beginning.

### CODE REVIEW

**Comment by sshine** [comment]
Thanks! I must admit that the source code still segfaults once you get it to compile. :-)

**Comment by gpiedimonte** [comment]
Yes but for me won’t compile whit -lcrypt at the beginning ^^

I have the same problem of segmentation fault… You did an amazing work whit those sources!

Ok, I dream of having it work for at least 25 years ^^

**Comment by sshine** [comment]
Haha, that's nice.

The reason I started studying computer science was because of DIKU MUD.

DIKU is Department of Computer Science, University of Copenhagen, and I live in Copenhagen.

I've delayed making it work further because I have to dig into C debugging at this point.

But I'd be interested in cooperating to make it runnable again.

My goal is to be as little invasive as possible, as if this were an archaeological experiment.

Going back to my earlier commits, I can see that I renamed `coma` into `coma_0` to avoid some name clash with modern GCC. But perhaps there is a way to shadow the modern `coma` in favor of renaming it.

**Comment by gpiedimonte** [comment]
Ok! Now it works! 

I’ve debugged line per line and I’ve fixed the dice method with a workaround :) DikuMud it WORKS!!! Hey We made it!
The problem is an assertion into the dice method. I’ll send you my “workaround” late.

You and me are friends now? :D hahahahaha

**Pull request merged**
